# Generated by Django 3.2.4 on 2021-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_alter_salary_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.ManyToManyField(to='employeeApp.Employee'),
        ),
    ]
