# Generated by Django 3.2.4 on 2021-06-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0004_auto_20210603_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(to='employeeApp.Project'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
